version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8-estudos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed_api
      #MYSQL_USER: exampleuser
      #MYSQL_PASSWORD: examplepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data: